In [5]:
import polars as pl
import os

In [16]:
ruta_data = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/Ruta a la electrificación de la Movilidad/Datos/2015_01.parquet"
)

In [26]:
ruta_data["CATEGORÍA_VEHÍCULO_ELÉCTRICO"].unique()

shape: (5,)
Series: 'CATEGORÍA_VEHÍCULO_ELÉCTRICO' [str]
[
	null
	"HEV"
	"PHEV"
	"BEV"
	"REEV"
]

In [28]:
personas = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/data/Personas_municipios_2022-01-01_2022-01-06_v2.parquet"
)
overnight = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/data/Pernoctaciones_municipios_2022-01-01_2022-01-06_v2.parquet"
)
trips = pl.read_parquet(
    "/Users/nicolaswilches/ds/projects/iberdrola-ev-network/data/Viajes_municipios_2022-01-01_2022-01-06_v2.parquet"
)

In [24]:
personas.head()

shape: (5, 6)
┌────────────┬─────────────────────┬──────┬────────┬─────────────────┬─────────┐
│ date       ┆ overnight_stay_area ┆ age  ┆ gender ┆ number_of_trips ┆ people  │
│ ---        ┆ ---                 ┆ ---  ┆ ---    ┆ ---             ┆ ---     │
│ str        ┆ str                 ┆ str  ┆ str    ┆ str             ┆ f64     │
╞════════════╪═════════════════════╪══════╪════════╪═════════════════╪═════════╡
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 0               ┆ 244.54  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 1               ┆ 34.94   │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 2               ┆ 64.971  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ male   ┆ 2+              ┆ 89.423  │
│ 2022-01-01 ┆ 01001               ┆ 0-25 ┆ female ┆ 0               ┆ 164.802 │
└────────────┴─────────────────────┴──────┴────────┴─────────────────┴─────────┘

In [29]:
overnight.head()

shape: (5, 4)
┌────────────┬────────────────┬─────────────────────┬──────────┐
│ date       ┆ residence_area ┆ overnight_stay_area ┆ people   │
│ ---        ┆ ---            ┆ ---                 ┆ ---      │
│ str        ┆ str            ┆ str                 ┆ f64      │
╞════════════╪════════════════╪═════════════════════╪══════════╡
│ 2022-01-01 ┆ 01001          ┆ 01001               ┆ 2447.613 │
│ 2022-01-01 ┆ 01001          ┆ 01017_AM            ┆ 9.0      │
│ 2022-01-01 ┆ 01001          ┆ 01047_AM            ┆ 2.514    │
│ 2022-01-01 ┆ 01001          ┆ 01051               ┆ 5.78     │
│ 2022-01-01 ┆ 01001          ┆ 01059               ┆ 181.97   │
└────────────┴────────────────┴─────────────────────┴──────────┘

In [30]:
trips.head()

shape: (5, 8)
┌────────────┬──────┬───────────┬──────────────┬─────────────┬─────────────┬─────────┬─────────────┐
│ date       ┆ hour ┆ id_origin ┆ id_destinati ┆ activity_or ┆ activity_de ┆ n_trips ┆ trips_total │
│ ---        ┆ ---  ┆ ---       ┆ on           ┆ igin        ┆ stination   ┆ ---     ┆ _length_km  │
│ str        ┆ i64  ┆ str       ┆ ---          ┆ ---         ┆ ---         ┆ f64     ┆ ---         │
│            ┆      ┆           ┆ str          ┆ str         ┆ str         ┆         ┆ f64         │
╞════════════╪══════╪═══════════╪══════════════╪═════════════╪═════════════╪═════════╪═════════════╡
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ home        ┆ other_frequ ┆ 2.605   ┆ 9.457       │
│            ┆      ┆           ┆              ┆             ┆ ent         ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ other_frequ ┆ home        ┆ 12.146  ┆ 65.663      │
│            ┆      ┆           ┆              ┆ ent         ┆             ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ other_frequ ┆ other_frequ ┆ 5.398   ┆ 32.272      │
│            ┆      ┆           ┆              ┆ ent         ┆ ent         ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ other_non_f ┆ home        ┆ 2.212   ┆ 5.645       │
│            ┆      ┆           ┆              ┆ requent     ┆             ┆         ┆             │
│ 2022-01-01 ┆ 0    ┆ 01001     ┆ 01009_AM     ┆ work_or_stu ┆ home        ┆ 1.041   ┆ 4.629       │
│            ┆      ┆           ┆              ┆ dy          ┆             ┆         ┆             │
└────────────┴──────┴───────────┴──────────────┴─────────────┴─────────────┴─────────┴─────────────┘

In [32]:
from pyspainmobility import Mobility, Zones
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
# getting 1 week of mobility data. In this case, we download the data from March 10 to March 16
mobility_data = Mobility(
    version=2, zones="lua", start_date="2024-10-14", end_date="2024-10-20"
)
# and we extract the OD matrices
mobility_data.get_od_data()

Downloading file from https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241014_Viajes_GAU.csv.gz
Downloading: https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241014_Viajes_GAU.csv.gz
Saved 97395065 bytes to /Users/nicolaswilches/data/20241014_Viajes_GAU_v2.csv.gz
Downloading file from https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241015_Viajes_GAU.csv.gz
Downloading: https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241015_Viajes_GAU.csv.gz
Saved 96276004 bytes to /Users/nicolaswilches/data/20241015_Viajes_GAU_v2.csv.gz
Downloading file from https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241016_Viajes_GAU.csv.gz
Downloading: https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241016_Viajes_GAU.csv.gz
Saved 96949774 bytes to /Users/nicolaswilches/data/20241016_Viajes_GAU_v2.csv.gz
Downloading file from https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241017_Viajes_GAU.csv.gz
Downloading: https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241017_Viajes_GAU.csv.gz
Saved 97771364 bytes to /Users/nicolaswilches/data/20241017_Viajes_GAU_v2.csv.gz
Downloading file from https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241018_Viajes_GAU.csv.gz
Downloading: https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241018_Viajes_GAU.csv.gz
Saved 103964535 bytes to /Users/nicolaswilches/data/20241018_Viajes_GAU_v2.csv.gz
Downloading file from https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241019_Viajes_GAU.csv.gz
Downloading: https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241019_Viajes_GAU.csv.gz
Saved 98889417 bytes to /Users/nicolaswilches/data/20241019_Viajes_GAU_v2.csv.gz
Downloading file from https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241020_Viajes_GAU.csv.gz
Downloading: https://movilidad-opendata.mitma.es/estudios_basicos/por-GAU/viajes/ficheros-diarios/2024-10/20241020_Viajes_GAU.csv.gz
Saved 94179460 bytes to /Users/nicolaswilches/data/20241020_Viajes_GAU_v2.csv.gz
Generating parquet file for ODs....

  0%|          | 0/7 [00:00<?, ?it/s]

Processing file: /Users/nicolaswilches/data/20241014_Viajes_GAU_v2.csv.gz
Reading gzipped file...

 14%|█▍        | 1/7 [00:24<02:25, 24.29s/it]

Processing file: /Users/nicolaswilches/data/20241015_Viajes_GAU_v2.csv.gz
Reading gzipped file...

 29%|██▊       | 2/7 [00:51<02:11, 26.27s/it]

Processing file: /Users/nicolaswilches/data/20241016_Viajes_GAU_v2.csv.gz
Reading gzipped file...

 43%|████▎     | 3/7 [01:26<01:59, 29.94s/it]

Processing file: /Users/nicolaswilches/data/20241017_Viajes_GAU_v2.csv.gz
Reading gzipped file...

 57%|█████▋    | 4/7 [02:02<01:37, 32.39s/it]

Processing file: /Users/nicolaswilches/data/20241018_Viajes_GAU_v2.csv.gz
Reading gzipped file...

 57%|█████▋    | 4/7 [02:25<01:49, 36.38s/it]

KeyboardInterrupt: